name: Release image

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true
        description: Version with syntax v0.9.9 or v0.9.9b4

concurrency:
  group: publish-images-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/thomasjpfan/union-sdk

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set environment variables
        id: env
        run: |
          UNION_VERSION=${RELEASE_VERSION//v/}  # Remove v
          echo "UNION_VERSION=$UNION_VERSION" >> $GITHUB_ENV
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:py${{ matrix.python-version }}-${{ env.UNION_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            UNION_VERSION=${{ env.UNION_VERSION }}
